In [57]:
import yfinance as yf

# Define the stock symbol and date range
sp500_tickers = [
    "AAPL", "MSFT", "AMZN", "GOOGL", "GOOG", "FB", "JPM", "TSLA", "V", "JNJ",
    "PG", "NVDA", "BRK.B", "HD", "MA", "UNH", "VZ", "PYPL", "DIS", "CRM",
    "INTC", "XOM", "CMCSA", "T", "WMT", "KO", "PFE", "MRK", "CSCO", "AAP",
    "COST", "NFLX", "CVX", "ABT", "MCD", "IBM", "GS", "SBUX", "CAT", "MO"
]

start_date = "2021-12-31" 
end_date = "2022-12-31"

ticker_dict = {}
quarterly_performance = {}

# Iterate through the list
for ticker in sp500_tickers:
    ticker_dict[ticker] = yf.download(ticker, start=start_date, end=end_date)
    
    try:
        temp_df = ticker_dict[ticker].copy()

        quarterly_data = temp_df['Adj Close'].resample('Q').ffill()

        quarterly_returns = quarterly_data.pct_change()

        # Store quarterly returns in the dictionary
        quarterly_performance[ticker] = quarterly_returns
        
    except Exception as e:
        print(f"Error processing data for {ticker}: {e}")

    # Store quarterly returns in the dictionary
    quarterly_performance[ticker] = quarterly_returns

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['FB']: Exception('%ticker%: No timezone found, symbol may be delisted')

Error processing data for FB: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['BRK.B']: Exception('%ticker%: No timezone found, symbol may be delisted')

Error processing data for BRK.B: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [58]:
ticker_dict['AAPL'].head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-12-31,178.089996,179.229996,177.259995,177.570007,175.795349,64062300
2022-01-03,177.830002,182.880005,177.710007,182.009995,180.190979,104487900
2022-01-04,182.630005,182.940002,179.119995,179.699997,177.904068,99310400
2022-01-05,179.610001,180.169998,174.639999,174.919998,173.171844,94537600
2022-01-06,172.699997,175.300003,171.639999,172.000000,170.281006,96904000

In [59]:
#quarterly returns for Apple, as an example
print("Quarterly Returns for AAPL:")
quarterly_performance['AAPL']

Quarterly Returns for AAPL:

Date
2021-12-31         NaN
2022-03-31   -0.015417
2022-06-30   -0.215847
2022-09-30    0.012229
2022-12-31   -0.058281
Freq: Q-DEC, Name: Adj Close, dtype: float64

In [75]:
#Adding the Daily ROI column
for df_idx in sp500_tickers:
    target_df = ticker_dict[df_idx]
    target_df['Daily_ROI'] = (target_df['Adj Close'] / target_df['Adj Close'].shift(1) - 1) * 100

#Testing to make sure the Daily ROI is correct
#Keep in mind the first value is none because there is no value beforehand
ticker_dict['AAPL'].head()

,Open,High,Low,Close,Adj Close,Volume,Daily_ROI
Date,,,,,,,
2021-12-31,178.089996,179.229996,177.259995,177.570007,175.795349,64062300,NaN
2022-01-03,177.830002,182.880005,177.710007,182.009995,180.190979,104487900,2.500424
2022-01-04,182.630005,182.940002,179.119995,179.699997,177.904068,99310400,-1.269160
2022-01-05,179.610001,180.169998,174.639999,174.919998,173.171844,94537600,-2.659986
2022-01-06,172.699997,175.300003,171.639999,172.000000,170.281006,96904000,-1.669347

In [76]:
#using pickle to export
import pickle

with open('ticker_prices.pkl', 'wb') as pickle_file:
    pickle.dump(ticker_dict, pickle_file)
    
with open('Quarter_prices.pkl', 'wb') as pickle_file:
    pickle.dump(quarterly_performance, pickle_file)

In [61]:
#testing to make sure this works
with open('ticker_prices.pkl', 'rb') as pickle_file:
    imported_dict = pickle.load(pickle_file)

print(imported_dict)

{'AAPL':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  178.089996  179.229996  177.259995  177.570007  175.795349
2022-01-03  177.830002  182.880005  177.710007  182.009995  180.190979
2022-01-04  182.630005  182.940002  179.119995  179.699997  177.904068
2022-01-05  179.610001  180.169998  174.639999  174.919998  173.171844
2022-01-06  172.699997  175.300003  171.639999  172.000000  170.281006
...                ...         ...         ...         ...         ...
2022-12-23  130.919998  132.419998  129.639999  131.860001  131.299820
2022-12-27  131.380005  131.410004  128.720001  130.029999  129.477585
2022-12-28  129.669998  131.029999  125.870003  126.040001  125.504539
2022-12-29  127.989998  130.479996  127.730003  129.610001  129.059372
2022-12-30  128.410004  129.949997  127.430000  129.929993  129.378006

               Volume
Date
2021-12-31   64062300
2022-01-03  104487900
2022-01-04   99310400
2022-01-05   94537600
2022-01-06   96904000
...               ...
2022-12-23   63814900
2022-12-27   69007800
2022-12-28   85438400
2022-12-29   75703700
2022-12-30   77034200

[252 rows x 6 columns], 'MSFT':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  338.510010  339.359985  335.850006  336.320007  330.939758
2022-01-03  335.350006  338.000000  329.779999  334.750000  329.394867
2022-01-04  334.829987  335.200012  326.119995  329.010010  323.746704
2022-01-05  325.859985  326.070007  315.980011  316.380005  311.318787
2022-01-06  313.149994  318.700012  311.489990  313.880005  308.858734
...                ...         ...         ...         ...         ...
2022-12-23  236.110001  238.869995  233.940002  238.729996  237.112076
2022-12-27  238.699997  238.929993  235.830002  236.960007  235.354080
2022-12-28  236.889999  239.720001  234.169998  234.529999  232.940552
2022-12-29  235.649994  241.919998  235.649994  241.009995  239.376648
2022-12-30  238.210007  239.960007  236.660004  239.820007  238.194702

              Volume
Date
2021-12-31  18000800
2022-01-03  28865100
2022-01-04  32674300
2022-01-05  40054300
2022-01-06  39646100
...              ...
2022-12-23  21207000
2022-12-27  16688600
2022-12-28  17457100
2022-12-29  19770700
2022-12-30  21938500

[252 rows x 6 columns], 'AMZN':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  168.955994  169.350006  166.558502  166.716995  166.716995
2022-01-03  167.550003  170.703506  166.160507  170.404495  170.404495
2022-01-04  170.438004  171.399994  166.349503  167.522003  167.522003
2022-01-05  166.882996  167.126495  164.356995  164.356995  164.356995
2022-01-06  163.450500  164.800003  161.936996  163.253998  163.253998
...                ...         ...         ...         ...         ...
2022-12-23   83.250000   85.779999   82.930000   85.250000   85.250000
2022-12-27   84.970001   85.349998   83.000000   83.040001   83.040001
2022-12-28   82.800003   83.480003   81.690002   81.820000   81.820000
2022-12-29   82.870003   84.550003   82.550003   84.180000   84.180000
2022-12-30   83.120003   84.050003   82.470001   84.000000   84.000000

              Volume
Date
2021-12-31  47830000
2022-01-03  63520000
2022-01-04  70726000
2022-01-05  64302000
2022-01-06  51958000
...              ...
2022-12-23  57433700
2022-12-27  57284000
2022-12-28  58228600
2022-12-29  54995900
2022-12-30  62401200

[252 rows x 6 columns], 'GOOGL':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  146.050003  146.698502  144.852005  144.852005  144.852005
2022-01-03  145.054993  145.850998  143.712997  144.991501  144.991501
2022-01-04  145.395996  146.485001  143.716507  144.399506  144.399506
2022-01-05  144.419998  144.499496  137.688004  137.774994  137.774994
2022-01-06  136.998505  139.940002  136.558502  137.747498  137.747498
...                ...         ...         ...         ...         ...
2022-12-23   87.110001   89.550003   87.070000   89.230003   89.230003
2022-12-27   88.800003   88.940002   87.010002   87.389999   87.389999
2022-12-28   86.980003   88.040001   85.940002   86.019997   86.019997
2022-12-29   86.620003   88.849998   86.610001   88.449997   88.449997
2022-12-30   86.980003   88.300003   86.570000   88.230003   88.230003

              Volume
Date
2021-12-31  18136000
2022-01-03  28646000
2022-01-04  28400000
2022-01-05  54618000
2022-01-06  37348000
...              ...
2022-12-23  23003000
2022-12-27  20097300
2022-12-28  19523200
2022-12-29  23333500
2022-12-30  23986300

[252 rows x 6 columns], 'GOOG':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  145.544006  146.365005  144.677505  144.679504  144.679504
2022-01-03  144.475494  145.550003  143.502502  145.074493  145.074493
2022-01-04  145.550507  146.610001  143.816147  144.416504  144.416504
2022-01-05  144.181000  144.298004  137.523499  137.653503  137.653503
2022-01-06  137.497498  139.686005  136.763504  137.550995  137.550995
...                ...         ...         ...         ...         ...
2022-12-23   87.620003   90.099998   87.620003   89.809998   89.809998
2022-12-27   89.309998   89.500000   87.535004   87.930000   87.930000
2022-12-28   87.500000   88.519997   86.370003   86.459999   86.459999
2022-12-29   87.029999   89.364998   86.989998   88.949997   88.949997
2022-12-30   87.364998   88.830002   87.029999   88.730003   88.730003

              Volume
Date
2021-12-31  17298000
2022-01-03  25214000
2022-01-04  22928000
2022-01-05  49642000
2022-01-06  29050000
...              ...
2022-12-23  17815000
2022-12-27  15470900
2022-12-28  17879600
2022-12-29  18280700
2022-12-30  19190300

[252 rows x 6 columns], 'FB': Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: [], 'JPM':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  158.449997  159.289993  157.960007  158.350006  150.161514
2022-01-03  159.860001  162.639999  159.509995  161.699997  153.338287
2022-01-04  164.309998  168.580002  164.229996  167.830002  159.151306
2022-01-05  167.820007  168.360001  163.729996  163.779999  156.241669
2022-01-06  166.910004  167.369995  163.869995  165.520004  157.901611
...                ...         ...         ...         ...         ...
2022-12-23  130.580002  131.440002  129.639999  131.279999  128.420670
2022-12-27  131.570007  132.220001  130.550003  131.740005  128.870667
2022-12-28  131.850006  133.410004  131.009995  132.460007  129.574982
2022-12-29  132.929993  133.270004  132.309998  133.220001  130.318420
2022-12-30  132.809998  134.330002  132.440002  134.100006  131.179276

              Volume
Date
2021-12-31   5805900
2022-01-03  13120900
2022-01-04  20195800
2022-01-05  17539400
2022-01-06  14047500
...              ...
2022-12-23   5091900
2022-12-27   5411000
2022-12-28   8827700
2022-12-29   6585200
2022-12-30   9292500

[252 rows x 6 columns], 'TSLA':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  357.813324  360.666656  351.529999  352.260010  352.260010
2022-01-03  382.583344  400.356659  378.679993  399.926666  399.926666
2022-01-04  396.516663  402.666656  374.350006  383.196655  383.196655
2022-01-05  382.216675  390.113342  360.336670  362.706665  362.706665
2022-01-06  359.000000  362.666656  340.166656  354.899994  354.899994
...                ...         ...         ...         ...         ...
2022-12-23  126.370003  128.619995  121.019997  123.150002  123.150002
2022-12-27  117.500000  119.669998  108.760002  109.099998  109.099998
2022-12-28  110.349998  116.269997  108.239998  112.709999  112.709999
2022-12-29  120.389999  123.570000  117.500000  121.820000  121.820000
2022-12-30  119.949997  124.480003  119.750000  123.180000  123.180000

               Volume
Date
2021-12-31   40733700
2022-01-03  103931400
2022-01-04  100248300
2022-01-05   80119800
2022-01-06   90336600
...               ...
2022-12-23  166989700
2022-12-27  208643400
2022-12-28  221070500
2022-12-29  221923300
2022-12-30  157777300

[252 rows x 6 columns], 'V':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  216.809998  217.979996  215.490005  216.710007  213.842758
2022-01-03  217.520004  222.059998  217.009995  221.429993  218.500305
2022-01-04  222.000000  226.789993  221.809998  222.460007  219.516708
2022-01-05  222.639999  225.270004  219.919998  220.000000  217.089218
2022-01-06  217.800003  221.910004  217.550003  219.750000  216.842560
...                ...         ...         ...         ...         ...
2022-12-23  204.130005  206.240005  203.520004  205.830002  204.643112
2022-12-27  205.919998  206.880005  204.600006  206.289993  205.100449
2022-12-28  206.679993  208.529999  204.800003  204.990005  203.807953
2022-12-29  205.949997  208.529999  205.500000  208.059998  206.860245
2022-12-30  206.309998  208.039993  205.699997  207.759995  206.561981

              Volume
Date
2021-12-31   4723300
2022-01-03   7694500
2022-01-04  10629300
2022-01-05   9594600
2022-01-06   7877500
...              ...
2022-12-23   3246000
2022-12-27   2904900
2022-12-28   3139200
2022-12-29   3675500
2022-12-30   4159400

[252 rows x 6 columns], 'JNJ':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  172.529999  172.679993  171.029999  171.070007  163.076736
2022-01-03  170.210007  171.600006  169.100006  171.539993  163.524765
2022-01-04  171.059998  172.289993  170.600006  171.080002  163.086273
2022-01-05  172.000000  173.470001  171.619995  172.220001  164.173004
2022-01-06  172.149994  172.500000  170.800003  171.630005  163.610580
...                ...         ...         ...         ...         ...
2022-12-23  176.669998  177.520004  175.809998  177.479996  173.632370
2022-12-27  178.110001  178.350006  176.990005  177.429993  173.583450
2022-12-28  177.759995  178.449997  176.649994  176.660004  172.830154
2022-12-29  177.550003  178.300003  177.070007  177.559998  173.710648
2022-12-30  177.490005  177.770004  175.399994  176.649994  172.820358

             Volume
Date
2021-12-31  4409500
2022-01-03  6012200
2022-01-04  6748400
2022-01-05  7016100
2022-01-06  7301600
...             ...
2022-12-23  3683400
2022-12-27  3067300
2022-12-28  2645400
2022-12-29  2828800
2022-12-30  4216600

[252 rows x 6 columns], 'PG':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  162.860001  163.729996  162.460007  163.580002  156.648193
2022-01-03  161.690002  162.940002  159.880005  162.899994  155.996964
2022-01-04  162.289993  164.389999  162.179993  163.470001  156.542816
2022-01-05  163.440002  165.320007  163.399994  164.210007  157.251480
2022-01-06  164.339996  165.199997  162.610001  162.830002  155.929932
...                ...         ...         ...         ...         ...
2022-12-23  152.309998  152.919998  151.669998  152.619995  149.780884
2022-12-27  152.699997  154.320007  152.660004  153.949997  151.086136
2022-12-28  154.279999  154.649994  151.899994  151.960007  149.133194
2022-12-29  152.809998  153.240005  152.139999  152.589996  149.751434
2022-12-30  152.429993  152.679993  150.440002  151.559998  148.740616

             Volume
Date
2021-12-31  5327000
2022-01-03  9317300
2022-01-04  9253800
2022-01-05  9330200
2022-01-06  7556000
...             ...
2022-12-23  3401800
2022-12-27  4215100
2022-12-28  4197500
2022-12-29  3809100
2022-12-30  4532000

[252 rows x 6 columns], 'NVDA':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  296.739990  300.299988  293.309998  294.109985  293.730713
2022-01-03  298.149994  307.109985  297.850006  301.209991  300.821564
2022-01-04  302.769989  304.679993  283.489990  292.899994  292.522339
2022-01-05  289.489990  294.160004  275.329987  276.040009  275.684082
2022-01-06  276.399994  284.380005  270.649994  281.779999  281.416656
...                ...         ...         ...         ...         ...
2022-12-23  151.960007  153.389999  148.830002  152.059998  152.005920
2022-12-27  150.740005  151.000000  140.559998  141.210007  141.159790
2022-12-28  139.270004  142.619995  138.839996  140.360001  140.310074
2022-12-29  144.020004  146.830002  142.270004  146.029999  145.978073
2022-12-30  143.339996  146.289993  142.330002  146.139999  146.088028

              Volume
Date
2021-12-31  26653000
2022-01-03  39154700
2022-01-04  52715400
2022-01-05  49806400
2022-01-06  45418600
...              ...
2022-12-23  34932600
2022-12-27  46490200
2022-12-28  35106600
2022-12-29  35492300
2022-12-30  31049000

[252 rows x 6 columns], 'BRK.B': Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: [], 'HD':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  409.989990  416.529999  409.890015  415.010010  396.509827
2022-01-03  416.570007  417.839996  403.260010  408.640015  390.423859
2022-01-04  408.640015  413.609985  408.190002  412.839996  394.436615
2022-01-05  414.000000  414.220001  406.809998  407.239990  389.086243
2022-01-06  408.559998  409.070007  403.019989  405.760010  387.672211
...                ...         ...         ...         ...         ...
2022-12-23  314.149994  319.100006  313.059998  318.730011  312.183167
2022-12-27  318.410004  321.549988  317.510010  319.549988  312.986298
2022-12-28  320.549988  321.429993  315.500000  315.730011  309.244751
2022-12-29  318.649994  321.829987  317.589996  320.410004  313.828613
2022-12-30  317.489990  318.170013  313.019989  315.859985  309.372070

             Volume
Date
2021-12-31  2386100
2022-01-03  3715700
2022-01-04  3266500
2022-01-05  4443200
2022-01-06  3315100
...             ...
2022-12-23  2064900
2022-12-27  1610200
2022-12-28  1568200
2022-12-29  1559100
2022-12-30  2581600

[252 rows x 6 columns], 'MA':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  357.950012  363.380005  356.779999  359.320007  355.575348
2022-01-03  359.790009  372.320007  359.250000  370.950012  367.084106
2022-01-04  371.989990  382.399994  371.649994  375.390015  371.477905
2022-01-05  374.000000  382.500000  372.510010  373.899994  370.003357
2022-01-06  368.690002  374.220001  366.500000  370.000000  366.624512
...                ...         ...         ...         ...         ...
2022-12-23  339.019989  344.540009  337.690002  343.600006  342.011322
2022-12-27  344.100006  346.910004  341.809998  346.160004  344.559479
2022-12-28  346.549988  349.510010  341.779999  341.950012  340.368958
2022-12-29  344.380005  349.720001  343.540009  348.209991  346.599976
2022-12-30  345.329987  347.899994  343.619995  347.730011  346.122253

             Volume
Date
2021-12-31  1984000
2022-01-03  4708200
2022-01-04  6854500
2022-01-05  5976600
2022-01-06  4781100
...             ...
2022-12-23  1914500
2022-12-27  1637700
2022-12-28  1854100
2022-12-29  1459800
2022-12-30  1617600

[252 rows x 6 columns], 'UNH':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  504.140015  506.869995  502.040009  502.140015  490.103363
2022-01-03  500.000000  502.899994  493.049988  502.279999  490.239899
2022-01-04  503.200012  503.750000  490.880005  490.899994  479.132721
2022-01-05  494.769989  497.000000  489.690002  489.690002  477.951721
2022-01-06  480.000000  484.140015  463.119995  469.649994  458.392090
...                ...         ...         ...         ...         ...
2022-12-23  524.099976  531.309998  522.900024  531.309998  525.215271
2022-12-27  533.929993  535.840027  529.849976  531.989990  525.887512
2022-12-28  535.070007  538.150024  527.729980  528.450012  522.388123
2022-12-29  532.539978  533.679993  528.859985  529.880005  523.801697
2022-12-30  530.000000  530.500000  524.840027  530.179993  524.098267

             Volume
Date
2021-12-31  1695400
2022-01-03  3033600
2022-01-04  3908100
2022-01-05  3921100
2022-01-06  6555200
...             ...
2022-12-23  1292300
2022-12-27  1596700
2022-12-28  1694200
2022-12-29  1379700
2022-12-30  1849600

[252 rows x 6 columns], 'VZ':                  Open       High        Low      Close  Adj Close    Volume
Date
2021-12-31  52.200001  52.310001  51.880001  51.959999  46.872158  15911400
2022-01-03  52.070000  52.560001  51.980000  52.439999  47.305149  18240100
2022-01-04  52.639999  53.709999  52.549999  53.470001  48.234291  26376800
2022-01-05  53.840000  54.639999  53.509998  54.020000  48.730438  28697300
2022-01-06  54.480000  54.549999  53.660000  53.759998  48.495895  21563800
...               ...        ...        ...        ...        ...       ...
2022-12-23  38.310001  38.540001  37.919998  38.410000  36.545631  16918300
2022-12-27  38.490002  39.400002  38.320000  39.250000  37.344864  25315900
2022-12-28  39.189999  39.660000  38.590000  38.810001  36.926220  21793200
2022-12-29  38.900002  39.529999  38.810001  39.259998  37.354374  17347000
2022-12-30  39.310001  39.689999  39.070000  39.400002  37.487583  44007200

[252 rows x 6 columns], 'PYPL':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  191.449997  192.229996  188.399994  188.580002  188.580002
2022-01-03  191.410004  196.000000  189.949997  194.940002  194.940002
2022-01-04  196.000000  196.100006  188.190002  191.139999  191.139999
2022-01-05  189.865005  194.250000  187.149994  187.160004  187.160004
2022-01-06  185.520004  195.000000  185.070007  192.270004  192.270004
...                ...         ...         ...         ...         ...
2022-12-23   68.050003   69.250000   67.709999   69.029999   69.029999
2022-12-27   68.959999   69.239998   67.680000   68.330002   68.330002
2022-12-28   68.120003   69.470001   67.292000   67.550003   67.550003
2022-12-29   68.389999   70.739998   68.220001   70.559998   70.559998
2022-12-30   69.480003   71.260002   69.059998   71.220001   71.220001

              Volume
Date
2021-12-31   7360400
2022-01-03  12788200
2022-01-04  14198000
2022-01-05  13227600
2022-01-06  14206300
...              ...
2022-12-23   9990400
2022-12-27  10323800
2022-12-28   8897600
2022-12-29  13143000
2022-12-30  10175700

[252 rows x 6 columns], 'DIS':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  155.869995  156.570007  154.740005  154.889999  154.889999
2022-01-03  155.830002  157.559998  155.360001  156.759995  156.759995
2022-01-04  158.589996  160.320007  155.550003  155.729996  155.729996
2022-01-05  156.520004  159.380005  155.100006  155.190002  155.190002
2022-01-06  156.240005  157.770004  153.679993  156.899994  156.899994
...                ...         ...         ...         ...         ...
2022-12-23   86.059998   88.070000   85.769997   88.010002   88.010002
2022-12-27   87.419998   87.940002   85.959999   86.370003   86.370003
2022-12-28   86.080002   86.690002   84.070000   84.169998   84.169998
2022-12-29   85.250000   88.239998   84.970001   87.180000   87.180000
2022-12-30   85.730003   87.120003   85.230003   86.879997   86.879997

              Volume
Date
2021-12-31   6410200
2022-01-03  10222800
2022-01-04  16582000
2022-01-05  12272100
2022-01-06  11095300
...              ...
2022-12-23  11171600
2022-12-27  11561400
2022-12-28  12399500
2022-12-29  13045100
2022-12-30  23231000

[252 rows x 6 columns], 'CRM':                   Open        High         Low       Close   Adj Close  \
Date
2021-12-31  254.470001  256.489990  253.630005  254.130005  254.130005
2022-01-03  255.009995  256.700012  248.649994  255.460007  255.460007
2022-01-04  256.850006  256.869995  243.399994  248.229996  248.229996
2022-01-05  236.169998  238.199997  227.309998  227.669998  227.669998
2022-01-06  228.039993  234.479996  226.050003  229.149994  229.149994

In [77]:
#testing to make sure importing works
imported_dict['NVDA']

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-12-31,296.739990,300.299988,293.309998,294.109985,293.730713,26653000
2022-01-03,298.149994,307.109985,297.850006,301.209991,300.821564,39154700
2022-01-04,302.769989,304.679993,283.489990,292.899994,292.522339,52715400
2022-01-05,289.489990,294.160004,275.329987,276.040009,275.684082,49806400
2022-01-06,276.399994,284.380005,270.649994,281.779999,281.416656,45418600
...,...,...,...,...,...,...
2022-12-23,151.960007,153.389999,148.830002,152.059998,152.005920,34932600
2022-12-27,150.740005,151.000000,140.559998,141.210007,141.159790,46490200
2022-12-28,139.270004,142.619995,138.839996,140.360001,140.310074,35106600
2022-12-29,144.020004,146.830002,142.270004,146.029999,145.978073,35492300
2022-12-30,143.339996,146.289993,142.330002,146.139999,146.088028,31049000