In [24]:
import yfinance as yf

# Define the stock symbol and date range
sp500_tickers = [
    "AAPL", "MSFT", "AMZN", "GOOGL", "GOOG", "FB", "JPM", "TSLA", "V", "JNJ",
    "PG", "NVDA", "BRK.B", "HD", "MA", "UNH", "VZ", "PYPL", "DIS", "CRM",
    "INTC", "XOM", "CMCSA", "T", "WMT", "KO", "PFE", "MRK", "CSCO", "AAP",
    "COST", "NFLX", "CVX", "ABT", "MCD", "IBM", "GS", "SBUX", "CAT", "MO"
]

start_date = "2023-01-01"  # Replace with your desired start date
end_date = "2023-09-15"    # Replace with your desired end date

ticker_dict = {}

# Iterate through the list
for ticker in sp500_tickers:
    ticker_dict[ticker] = yf.download(stock_symbol, start=start_date, end=end_date)

# Extract opening and closing prices
#opening_prices = stock_data['Open']
#closing_prices = stock_data['Close']

# Print the collected data
#print("Opening Prices:")
#print(opening_prices)

#print("\nClosing Prices:")
#print(closing_prices)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [28]:
#testing a random dictionary key to see if it returns a dataframe as a value
ticker_dict['AAPL']

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-01-03,130.279999,130.899994,124.169998,125.070000,124.538666,112117500
2023-01-04,126.889999,128.660004,125.080002,126.360001,125.823189,89113600
2023-01-05,127.129997,127.769997,124.760002,125.019997,124.488876,80962700
2023-01-06,126.010002,130.289993,124.889999,129.619995,129.069321,87754700
2023-01-09,130.470001,133.410004,129.889999,130.149994,129.597061,70790800
...,...,...,...,...,...,...
2023-09-08,178.350006,180.240005,177.789993,178.179993,178.179993,65551300
2023-09-11,180.070007,180.300003,177.339996,179.360001,179.360001,58953100
2023-09-12,179.490005,180.130005,174.820007,176.300003,176.300003,90370200
2023-09-13,176.509995,177.300003,173.979996,174.210007,174.210007,84267900
2023-09-14,174.000000,176.100006,173.580002,175.740005,175.740005,60895800

In [31]:
#using pickle to export
import pickle

with open('ticker_prices.pkl', 'wb') as pickle_file:
    pickle.dump(ticker_dict, pickle_file)

In [34]:
#testing to make sure this works
with open('ticker_prices.pkl', 'rb') as pickle_file:
    imported_dict = pickle.load(pickle_file)

print(imported_dict)

{'AAPL':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538666
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'MSFT':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538658
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'AMZN':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538666
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'GOOGL':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538658
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'GOOG':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538658
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'FB':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538658
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'JPM':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538666
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'TSLA':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538658
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'V':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538666
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'JNJ':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538666
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'PG':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538666
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'NVDA':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538658
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488869
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069336
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597076
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'BRK.B':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538658
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'HD':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538658
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'MA':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538666
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'UNH':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538658
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'VZ':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538666
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.488876
2023-01-06  126.010002  130.289993  124.889999  129.619995  129.069321
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.597061
...                ...         ...         ...         ...         ...
2023-09-08  178.350006  180.240005  177.789993  178.179993  178.179993
2023-09-11  180.070007  180.300003  177.339996  179.360001  179.360001
2023-09-12  179.490005  180.130005  174.820007  176.300003  176.300003
2023-09-13  176.509995  177.300003  173.979996  174.210007  174.210007
2023-09-14  174.000000  176.100006  173.580002  175.740005  175.740005

               Volume
Date
2023-01-03  112117500
2023-01-04   89113600
2023-01-05   80962700
2023-01-06   87754700
2023-01-09   70790800
...               ...
2023-09-08   65551300
2023-09-11   58953100
2023-09-12   90370200
2023-09-13   84267900
2023-09-14   60895800

[176 rows x 6 columns], 'PYPL':                   Open        High         Low       Close   Adj Close  \
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.538666
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.823189

In [37]:
#testing to make sure importing works
imported_dict['NVDA']

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-01-03,130.279999,130.899994,124.169998,125.070000,124.538658,112117500
2023-01-04,126.889999,128.660004,125.080002,126.360001,125.823189,89113600
2023-01-05,127.129997,127.769997,124.760002,125.019997,124.488869,80962700
2023-01-06,126.010002,130.289993,124.889999,129.619995,129.069336,87754700
2023-01-09,130.470001,133.410004,129.889999,130.149994,129.597076,70790800
...,...,...,...,...,...,...
2023-09-08,178.350006,180.240005,177.789993,178.179993,178.179993,65551300
2023-09-11,180.070007,180.300003,177.339996,179.360001,179.360001,58953100
2023-09-12,179.490005,180.130005,174.820007,176.300003,176.300003,90370200
2023-09-13,176.509995,177.300003,173.979996,174.210007,174.210007,84267900
2023-09-14,174.000000,176.100006,173.580002,175.740005,175.740005,60895800